### ISSUE TITLE
has plan do add code coverage?

### ISSUE THREAD

**Issue by Pompeu** [vinyguedess/filebaser#1]
like istanbul ?
https://www.npmjs.com/package/istanbul

**Comment by vinyguedess** [comment]
Trap,
Something in mind ?

**Comment by rodrigooler** [comment]
It is highly recommended to use code coverage, ıstanbul seems interesting.

**Comment by vinyguedess** [comment]
Recently added codecoverage combined with istanbul.
Thanks for the tip guys.
